---
title: Canlis
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: jeremy@jeremypbeasley.com
description: Landmark fine-dining destination (since 1950s) offering Pacific NW fare
  in a midcentury-modern home.
baseurl: 
url: new.canlis.com
twitter_username: canlis
github_username: jeremypbeasley
markdown: kramdown
exclude:
- Gemfile.lock
gems:
- jekyll-assets
assets:
  cache: false
  autowrite: true
  prefix: "/assets"
  digest: false
  assets:
  - "*.png"
  - "*.jpg"
  - "*.svg"
  - "*.otf"
  - "*.ttf"
  - "*.woff"
  - "*.woff2"
  - "*.eot"
  - master.css
  - master.js
  sources:
  - assets/
  - assets/_img
  - assets/_fonts
